DOMAIN = "rtl_433"
STATUS_CMD = 3
START_CMD = 6
STOP_CMD = 7
CONFIG_CMD = 16
DISMISS_ALERT_CMD = 10
TAP_ID = "ID of Tap"
GW_ID = "ID of Gateway"
WS_HOST = "192.168.0.100:9443"
WS_IP = "192.1688.0.100"
WS_PORT = 9443
NAME = "Friendly Name of SDR"
DEFAULT_TIME = 15
DEFAULT_NAME = "RTL_433 HTTP Integration"
DEFAULT_VOL = 0
PLATFORMS = ['number', 'binary_sensor', 'sensor', 'switch']
ATTR_DEFAULT_TIME = 'Default Time'
ATTR_VOL = "Watering by Volume"
ATTR_DURATION = "Watering Duration"
ATTR_VOLUME = "Watering Volume"
ATTR_STATE = "is_watering"
MANUFACTURER = "RTL_SDR"
